# Generated by Django 2.1 on 2019-07-25 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('todo_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('due_date', models.DateTimeField(null=True, verbose_name='due_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Category')),
            ],
        ),
    ]
