# Generated by Django 2.1 on 2019-07-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateField(default='2019-07-22'),
        ),
    ]
