# Generated by Django 2.1 on 2019-08-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='email_notification',
            field=models.EmailField(max_length=500, null=True),
        ),
    ]
