# Generated by Django 2.1 on 2019-07-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190722_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateField(verbose_name='date_created'),
        ),
    ]
