# Generated by Django 2.1 on 2019-08-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_notification_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification_time',
            new_name='NotificationTime',
        ),
        migrations.AddField(
            model_name='todo',
            name='notification_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.NotificationTime'),
        ),
    ]
