# Generated by Django 2.1 on 2019-07-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190722_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
    ]
