# Generated by Django 2.1 on 2019-08-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190805_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='notification_time',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
