# Generated by Django 2.1 on 2019-07-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190722_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='due_date'),
        ),
    ]
