# Generated by Django 2.1 on 2019-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20190805_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sent_reminder',
            field=models.BooleanField(null=True),
        ),
    ]
