# Generated by Django 2.1 on 2019-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20190810_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sent_reminder',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
