# Generated by Django 2.1 on 2019-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20190810_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sent_reminder',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
